server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\\Users\\jk\\develop\\IdeaProjects\\native-local-repo
        git:
#          uri: file:///C:\\Users\\jk\\develop\\IdeaProjects\\git-local-repo
          uri: https://github.com/FireChilde/spring-cloud-config
          default-label: master


